apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-java
  labels:
    app: docker-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-java
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3030"
        prometheus.io/path: /metrics
      labels:
        app: docker-java
    spec:
      containers:
        - name: docker-java
          image: lichuan33/docker-java
          imagePullPolicy: Always
          ports:
            - name: http-web
              containerPort: 9090
          resources:
            limits:
              cpu: 10m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - operator: "Exists"
          effect: "NoExecute"
        - operator: "Exists"
          effect: "NoSchedule"
